Map flags = {
  'Punjabi (Shanmukhi script, Pakistan)': '🇵🇰',
  'Polish': '🇵🇱',
  'Pushto': '🇦🇫',
  'Potuguese': '🇵🇹',
  'Romanian': '🇷🇴',
  'Russian': '🇷🇺',
  'Sinhala': '🇱🇰',
  'Slovakian': '🇸🇰',
  'Slovenian': '🇸🇮',
  'Somali': '🇸🇴',
  'Albanian': '🇦🇱',
  'Serbian': '🇷🇸',
  'Swedish': '🇸🇪',
  'Tamil': '🇱🇰',
  'Telugu': '🇮🇳',
  'Thai': '🇹🇭',
  'Tagalog': '🇵🇭',
  'Turkish': '🇹🇷',
  'Ukrainian': '🇺🇦',
  'Urdu': '🇵🇰',
  'Vietnamese': '🇻🇳',
  'Simplified Chinese': '🇨🇳',
  'Traditional Chinese': '🇨🇳',
  'Afrikaans': '🇿🇦',
  'Arabic': '🇸🇦',
  'Azerbaijani': '🇦🇿',
  'Bashkir': '🇷🇺',
  'Belarusian': '🇧🇾',
  'Bulgarian': '🇧🇬',
  'Bengali': '🇧🇩',
  'Catalan': '🇦🇩',
  'Czech': '🇨🇿',
  'Chuvash': '🇷🇺',
  'Danish': '🇩🇰',
  'German': '🇩🇪',
  'Greek': '🇬🇷',
  'English': '🇺🇸',
  'Esperanto': '🇪🇸',
  'Spanish': '🇪🇸',
  'Estonian': '🇪🇪',
  'Basque': '🇪🇸',
  'Persian': '🇮🇷',
  'Finnish': '🇫🇮',
  'French': '🇫🇷',
  'Irish': '🇮🇪',
  'Gujarati': '🇮🇳',
  'Hebrew': '🇮🇱',
  'Hindi': '🇮🇳',
  'Croatian': '🇭🇷',
  'Haitian': '🇭🇹',
  'Hungarian': '🇭🇺',
  'Armenian': '🇦🇲',
  'Icelandic': '🇮🇸',
  'Italian': '🇮🇹',
  'Japanese': '🇯🇵',
  'Georgian': '🇬🇪',
  'Kazakh': '🇰🇿',
  'Central Khmer': '🇰🇿',
  'Korean': '🇰🇷',
  'Kurdish': '🇹🇷',
  'Kirghiz': '🇰🇬',
  'Lao': '🇱🇦',
  'Lithuanian': '🇱🇹',
  'Latvian': '🇱🇻',
  'Malayalam': '🇮🇳',
  'Mongolian': '🇲🇳',
  'Marathi': '🇮🇳',
  'Malay': '🇲🇾',
  'Maltese': '🇲🇹',
  'Burmese': '🇲🇲',
  'Norwegian Bokmal': '🇳🇴',
  'Nepali': '🇳🇵',
  'Dutch': '🇳🇱',
  'Norwegian Nynorsk': '🇳🇴',
  'Punjabi': '🇵🇰'
};
